### ISSUE TITLE
problem with type of missions

### ISSUE THREAD

**Issue by aurelbdx** [Romanito/NeoFlyExport#1]
Hi, thanks for this great small program!

 it doesn't work if I don't remove mission 7,8,9 (drop zone, tourists) in the log.
https://www.dropbox.com/s/hhf7byqn71qr2vl/neofly.png?dl=0
https://www.dropbox.com/s/qmm9ufrcjd26hnp/neofly1.png?dl=0

**Comment by Romanito** [comment]
@aurelbdx thanks for your report!
The fix is available in v1.0.2.

**Comment by aurelbdx** [comment]
great news! thanks :)
