### ISSUE TITLE
Problem with v1.1 (The format of the input string is incorrect)

### ISSUE THREAD

**Issue by aurelbdx** [Romanito/NeoFlyExport#2]
Hi,

it doesn't work since the last update. The format of the input string is incorrect.
https://www.dropbox.com/s/9raw7lrer5es90p/neofly_export.png?dl=0

maybe a decimal symbol problem

**Comment by Romanito** [comment]
I guess indeed. I had the problem and solved it on my PC by using a invariant culture format, but it seems this fix isn't working everywhere.
Thanks for the report.

**Comment by aurelbdx** [comment]
If it can help!

************** Texte de l'exception **************
System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à System.Double.Parse(String s, IFormatProvider provider)
   à NeoFlyExport.NeoFlyData.Load()
   à NeoFlyExport.MainForm.MainForm_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NeoFlyExport
    Version de l'assembly : 1.1.0.0
    Version Win32 : 1.1.0.0
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/NeoFlyExport.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.Data.Sqlite
    Version de l'assembly : 5.0.1.0
    Version Win32 : 5.0.120.57509
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/Microsoft.Data.Sqlite.DLL
----------------------------------------
netstandard
    Version de l'assembly : 2.0.0.0
    Version Win32 : 4.8.3752.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
SQLitePCLRaw.core
    Version de l'assembly : 2.0.4.976
    Version Win32 : 2.0.4.976
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/SQLitePCLRaw.core.DLL
----------------------------------------
SQLitePCLRaw.batteries_v2
    Version de l'assembly : 2.0.4.976
    Version Win32 : 2.0.4.976
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/SQLitePCLRaw.batteries_v2.DLL
----------------------------------------
SQLitePCLRaw.provider.dynamic_cdecl
    Version de l'assembly : 2.0.4.976
    Version Win32 : 2.0.4.976
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/SQLitePCLRaw.provider.dynamic_cdecl.DLL
----------------------------------------
System.Memory
    Version de l'assembly : 4.0.1.1
    Version Win32 : 4.6.27617.02
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/System.Memory.DLL
----------------------------------------
SQLitePCLRaw.nativelibrary
    Version de l'assembly : 2.0.4.976
    Version Win32 : 2.0.4.976
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/SQLitePCLRaw.nativelibrary.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
Windows.Storage
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/SysNative/WinMetadata/Windows.Storage.winmd
----------------------------------------
Windows.Foundation
    Version de l'assembly : 255.255.255.255
    Version Win32 : 10.0.10011.16384
    CodeBase : file:///C:/WINDOWS/SysNative/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0 built by: NET48REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.ValueTuple
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l'assembly : 4.0.4.1
    Version Win32 : 4.6.26919.02
    CodeBase : file:///E:/Aurel/Programmes/NeoFlyExport/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.3752.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>
